function createfigure(XMatrix1, YMatrix1, EMatrix1)
%CREATEFIGURE(XMATRIX1, YMATRIX1, EMATRIX1)
%  XMATRIX1:  errorbar x matrix
%  YMATRIX1:  errorbar y matrix
%  EMATRIX1:  errorbar e matrix

%  Auto-generated by MATLAB on 04-Nov-2015 13:29:55

% Create figure
figure1 = figure;
colormap('jet');

% Create axes
axes1 = axes('Parent',figure1,...
    'OuterPosition',[0.294047614470834 0 0.705952385529166 1]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1395]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
hold(axes1,'on');

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(XMatrix1,YMatrix1,EMatrix1);
set(errorbar1(1),'DisplayName','CHRCIS4','Color',[1 0.5 0]);
set(errorbar1(2),'DisplayName','CHRCIS3','Color',[1 1 0]);
set(errorbar1(3),'DisplayName','CHRCIS2','Color',[0.5 1 0.5]);
set(errorbar1(4),'DisplayName','CHRCIS1','Color',[0 1 1]);
set(errorbar1(5),'DisplayName','CHRCON2','Color',[0 0.5 1]);

% Create text
text('Parent',axes1,'Units','normalized',...
    'String','p value = 0.038215    0.001384',...
    'Position',[0.75 0.92 0]);

% Create xlabel
xlabel('Time [min]');

% Create ylabel
ylabel('Area [\mum^2]');

% Create title
title('YL006180315CHR1D06SK2a Area over time');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwestoutside','FontSize',6);

% Create colorbar
colorbar('peer',axes1);

